baseURL = 'https://mikan-foundation.org/archives'
languageCode = 'ja-jp'
defaultContentLanguage = "ja"
title = 'Mikan Labo Documents'

menu = 'main'

pygmentsCodeFences = true

[taxonomies]
tag = "tags"
caterogy = "categories"

[params.taxonomy]
taxonomyCloud = ["tags", "categories"]
taxonomyCloudTitle = ["Tag Cloud", "categories"]
taxonomyPageHeader = ["tags", "categories"]

[module]
[module.hugoVersion]
extended = true
min = '0.73.0'
[[module.imports]]
path = 'github.com/google/docsy'
disable = false
[[module.imports]]
path = 'github.com/google/docsy/dependencies'
disable = false

[markup]
	[markpup.goldmark]
		[markup.goldmark.rendere]
			unsafe = true
	[markup.highlight]
		style="tango"

[params]
copyright = "一般社団法人未完"
privacy_policy = "https://mikan-foundation.org/privacy-policy"

github_repo = "https://github.com/mikan-foundation/mikan-docs"

gcs_engine_id = "4c5072657b7d3f388"

algolia_docsearch = false

[params.links]
[[params.links.user]]
name = "Twitter"
url = "http://twitter.com/mikan_prj"
icon = "fab fa-twitter"
desc = "Twitter"

[params.ui]
breadcrumb_disable = false
footer_about_disable = false
navbar_logo = true
sidebar_menu_compact = false
sidebar_search_disable = false

[params.ui.feedback]
enable = true

[params.ui.readingtime]
enable = true


